ai_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from website.sitemaps import StaticViewSitemap
from django.views.generic import TemplateView
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

sitemaps = {
    "posts": PostSitemap,
    "static": StaticViewSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
    path('blog/', include('blog.urls', namespace='blog')),
    

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('djga/', include('google_analytics.urls')),
    path('robots.txt', include('robots.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'website.views.error_400'  # bad_request
handler403 = 'website.views.error_403'  # permission_denied
handler404 = 'website.views.error_404'  # page_not_found
handler500 = 'website.views.error_500'  # server_error

blog/urls.py
from . import views
from django.urls import path,include
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path('', views.PostIndex, name='index'),
    path('tag/<str:tag_slug>',views.PostIndex,name='index_tag'),
    path('category/<str:cat_slug>',views.PostIndex,name='index_category'),
    path('<str:slug>/', views.PostDetail, name='single'),
    path("feed/rss", LatestPostsFeed(), name="feed"),
]

website/urls.py
from . import views
from django.urls import path

app_name = "website"

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact_view, name='contact'),
    path('about', views.about_view, name='about'),
    path('resume', views.resume, name='resume'),
    path('rules', views.rules, name='rules'),
    path('privacy', views.privacy, name='privacy'),
    
]

templates/base.html
{% load static %}
{% load meta %}
{% load google_analytics_tags %}
{% load recaptcha2 %}
<!DOCTYPE html>
<html lang="fa-IR" {% meta_namespaces_schemaorg %}>

<head {% meta_namespaces %}>
    {% include "meta/meta.html" %}
    {% block title %}
    {% endblock title %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Material Portfolio Template Demo</title>
    <meta name="description" content="Demo of Material design portfolio template by TemplateFlip.com." />
    <link
        href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;amp;lang=en"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css" rel="stylesheet">
    <link href="{% static 'css/roboto_fonts.css' %}" rel="stylesheet">
    <link href="{% static 'css/material.indigo-pink.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/icon.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    {% block styles %}
    {% endblock styles %}
    {% recaptcha_init %}
</head>

<body id="top">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header mdl-layout__header--waterfall site-header">
            <div class="mdl-layout__header-row site-logo-row"><span class="mdl-layout__title">
                    <div class="site-logo"></div><span class="site-description">Material Design Portfolio</span>
                </span></div>
            <div class="mdl-layout__header-row site-navigation-row mdl-layout--large-screen-only">
                <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                    <a class="mdl-navigation__link" href="{% url 'website:index' %}">Home</a>
                    <a class="mdl-navigation__link" href="{% url 'website:resume' %}">Resume</a>
                    <a class="mdl-navigation__link" href="{% url 'blog:index' %}">blog</a>
                    <a class="mdl-navigation__link" href="{% url 'website:about' %}">About</a>
                    <a class="mdl-navigation__link" href="{% url 'website:contact' %}">Contact</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer mdl-layout--small-screen-only">
            <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                <a class="mdl-navigation__link" href="{% url 'website:index' %}">Home</a>
                <a class="mdl-navigation__link" href="{% url 'website:resume' %}">Resume</a>
                <a class="mdl-navigation__link" href="{% url 'blog:index' %}">blog</a>
                <a class="mdl-navigation__link" href="{% url 'website:about' %}">About</a>
                <a class="mdl-navigation__link" href="{% url 'website:contact' %}">Contact</a>
            </nav>
        </div>
        <main class="mdl-layout__content">
            <div class="site-content">

                {% block content %}
                {% endblock content %}

            </div>
            <footer class="mdl-mini-footer">
                <div class="footer-container">
                    <div class="mdl-logo">&copy; Unitiled. Design: <a href="#" target="_blank">TemplateFlip</a></div>
                    <ul class="mdl-mini-footer__link-list">
                        <li><a href="#">Privacy & Terms</a></li>
                    </ul>
                </div>
            </footer>
        </main>
        <script src="{% static 'js/material.min.js' %}" defer></script>
        {% block javascripts %}
        {% endblock javascripts %}
    </div>
</body>

</html>